Darbas/Darbas/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Darbas.Models;

namespace Darbas.Controllers
{
    //[Authorize(Roles = "A")]
    public class AdminController : Controller
    {
        private DuombazeEntities db = new DuombazeEntities();
        private bool exists = false;
        Pamoka temp;
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
        #region Pamoka

        // GET: Pamoka
        [HttpGet]
        public ActionResult Prideti()
        {
            IEnumerable<SelectListItem> items = db.Kategorijas.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.KategorijosPavadinimas
            });
            ViewData["JobTitle"] = items;
            return View();
        }

        [HttpPost, ActionName("Prideti")]
        public ActionResult PridetiPatvirtinimas(Pamoka pamoka, HttpPostedFileBase Failas)
        {
            IEnumerable<SelectListItem> items = db.Kategorijas.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.KategorijosPavadinimas
            });
            ViewData["JobTitle"] = items;
            if (ModelState.IsValid)
            {
                if (pamoka.Pavadinimas != null)
                {
                    if (Failas != null)
                    {
                        var id = db.Pamokas.ToList().Count;
                        pamoka.Id = id + 1;
                        string withOutSpecialCharacters =
                            new string(Failas.FileName.Where(c => char.IsLetterOrDigit(c) || c == '.').ToArray());
                        foreach (var pam in db.Pamokas)
                        {
                            if (pam.FailoPavadinimas.Equals(withOutSpecialCharacters))
                            {
                                exists = true;
                                break;
                            }
                        }
                        if (!exists)
                        {
                            Process(Failas);
                            pamoka.FailoPavadinimas = withOutSpecialCharacters;
                            if (pamoka.VideoNuoroda != null)
                            {
                                var a = CheckIfEmbed(pamoka.VideoNuoroda);
                                pamoka.VideoNuoroda = a;
                            }
                            foreach (Darbas.Kategorija KAT in db.Kategorijas)
                            {
                                if (pamoka.KategorijosID == KAT.Id)
                                {
                                    KAT.PamokuSkaicius++;
                                }
                                db.Kategorijas.AddOrUpdate(KAT);
                            }
                            db.Pamokas.Add(pamoka);
                            db.SaveChanges();
                            TempData["Ikelta"] = "Pamoka sekmingai prideta! Galite grizti i sarasa..";
                        }
                        else
                        {
                            TempData["Failas"] = "Failas egzistuoja tokiu vardu.";
                        }
                    }
                    else
                    {
                        TempData["Nepasirinktas"] = "Nepasirinktas joks failas";
                    }
                }
                else
                {
                    TempData["Klaida"] = "Nepavyko issaugoti pamokos.";
                }
            }
            return View();
        }

        [HttpGet]
        public ActionResult AdminSarasas()
        {
            var da = db.Pamokas.ToList();
            return View(da);
        }

        [HttpGet]
        public ActionResult Redaguoti(int id)
        {
            IEnumerable<SelectListItem> items = db.Kategorijas.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.KategorijosPavadinimas
            });
            ViewData["JobTitle"] = items;
            Pamoka pamoka = db.Pamokas.Single(pam => pam.Id == id);

            return View(pamoka);
        }

        [HttpPost, ActionName("Redaguoti")]
        [ValidateAntiForgeryToken]
        public ActionResult RedaguotiPatvirtinimas(Pamoka pamoka)
        {
            temp = db.Pamokas.Single(pam => pam.Id == pamoka.Id);
            IEnumerable<SelectListItem> items = db.Kategorijas.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.KategorijosPavadinimas
            });
            ViewData["JobTitle"] = items;
            if (ModelState.IsValid)
            {
                if (temp.KategorijosID != pamoka.KategorijosID)
                {
                    var id = temp.KategorijosID;
                    var kategorija = db.Kategorijas.Single(kat => kat.Id == id);
                    kategorija.PamokuSkaicius = kategorija.PamokuSkaicius - 1;
                    db.Kategorijas.AddOrUpdate(kategorija);
                }
                db.Pamokas.AddOrUpdate(pamoka);
                db.SaveChanges();
                TempData["Ikelta"] = "Sekmingai atnaujinta";
            }
            else
            {
                TempData["Klaida"] = "Ivyko klaida.";
            }
            return View();
        }

        [HttpGet]
        public ActionResult Trinti(int id)
        {
            Pamoka pamoka = db.Pamokas.Single(pam => pam.Id == id);
            return View(pamoka);
        }

        [HttpPost, ActionName("Trinti")]
        [ValidateAntiForgeryToken]
        public ActionResult TrintiPatvirtinimas(int id)
        {
            Pamoka pamoka = db.Pamokas.Find(id);
            var fileName = pamoka.FailoPavadinimas;
            var fullPath = Server.MapPath("~/Pamoka/Detales/" + fileName);
            temp = pamoka;
            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
                ViewBag.deleteSuccess = "true";
            }
            var kategorijosID = temp.KategorijosID;
            var kategorija = db.Kategorijas.Single(kat => kat.Id == kategorijosID);
            kategorija.PamokuSkaicius = kategorija.PamokuSkaicius - 1;
            db.Kategorijas.AddOrUpdate(kategorija);
            db.Pamokas.Remove(pamoka);
            db.SaveChanges();
            return RedirectToAction("AdminSarasas");
        }

        private bool isValid(string contentType)
        {
            return contentType.Equals("application/pdf");
        }

        private bool isValidLength(int contentLength)
        {
            return ((contentLength / 1024) / 1024 < 1);
        }

        public void Process(HttpPostedFileBase Failas)
        {
            if (!isValid(Failas.ContentType))
            {
                TempData["PDF"] = "Tik PDF failai";
            }
            else if (!isValidLength(Failas.ContentLength))
            {
                TempData["Dydis"] = "Too large";
            }
            else
            {
                if (Failas.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(Failas.FileName);
                    string withOutSpecialCharacters = new string(fileName.Where(c => char.IsLetterOrDigit(c) || c == '.').ToArray());
                    var path = Path.Combine(Server.MapPath("~/Pamoka/Detales/"), withOutSpecialCharacters);
                    Failas.SaveAs(path);
                    ViewBag.fileName = fileName;
                }
            }
        }

        public string CheckIfEmbed(string url)
        {
            if (url.Contains("youtube.com/embed/"))
            {
            }
            else
            {
                url.Replace("youtube.com", "youtube.com/embed/");
            }
            return url;
        }
        #endregion

        #region Kategorija

        [HttpGet]
        public ActionResult Kategorijos()
        {
            List<Kategorija> kategorijos = db.Kategorijas.ToList();
            return View(kategorijos);
        }


        [HttpGet]
        public ActionResult PridetiKategorija()
        {
            return View();
        }

        [HttpGet]
        public ActionResult TrintiKategorija(int id)
        {
            Kategorija kategorija = db.Kategorijas.Single(kat => kat.Id == id);
            return View(kategorija);
        }

        [HttpPost, ActionName("TrintiKategorija")]
        [ValidateAntiForgeryToken]
        public ActionResult TrintiKategorijaPatvirtinimas(int id)
        {
            Kategorija category = db.Kategorijas.Find(id);
            db.Kategorijas.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult PridetiKategorija(Kategorija kategorija)
        {
            bool exists = false;
            if (ModelState.IsValid)
            {
                if (kategorija.KategorijosPavadinimas != null)
                {
                    foreach (var cat in db.Kategorijas)
                    {
                        if (cat.KategorijosPavadinimas.Equals(kategorija.KategorijosPavadinimas))
                        {
                            exists = true;
                            break;
                        }
                    }
                    if (!exists)
                    {
                        var id = db.Kategorijas.ToList().Count;
                        kategorija.Id = id + 1;
                        kategorija.PamokuSkaicius = 0;
                        db.Kategorijas.Add(kategorija);
                        var resp = db.SaveChanges();

Darbas/Darbas/Controllers/PamokaController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Darbas.Views.Kategorija
{
    public class PamokaController : Controller
    { 
        DuombazeEntities db = new DuombazeEntities();
        private bool exists = false;
        Pamoka temp;
        // GET: Pamoka

        [HttpGet]
        public ActionResult Sarasas(int id)
        {
            var da = db.Pamokas.Where(pam => pam.KategorijosID == id);
            return View(da);
        }

        [HttpGet]
        public ActionResult Detales(int id)
        {
            Pamoka pamoka = db.Pamokas.Single(pam => pam.Id == id);
            return View(pamoka);
        }

       

    }
}

Darbas/Darbas/Views/Admin/AdminSarasas.cshtml
@using Darbas.Models

@model IEnumerable<Darbas.Pamoka>

@{
    ViewBag.Title = "Sarasas";
}

<h2>Sarasas</h2>
<div>
    <ul>
        @foreach (Pamoka pamoka in Model)
        {
            <li>
                @Html.ActionLink(pamoka.Pavadinimas, "Detales", new { @id = pamoka.Id }, null) @pamoka.Id,@pamoka.Pavadinimas,@pamoka.FailoPavadinimas,@pamoka.PraktikosID |
                @Html.ActionLink("Redaguoti", "Redaguoti", new { @id = pamoka.Id })|
                @Html.ActionLink("Trinti", "Trinti", new { @id = pamoka.Id })|
            </li>
        }
    </ul>
</div>
@Html.ActionLink("atgal i panele", "Index")

Darbas/Darbas/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Admin</h2>
<br />
<label>Kategorijos:</label>
<div>
    <div>
        @Html.ActionLink("Prideti kategorija", "PridetiKategorija")
    </div>
    <div>
        @Html.ActionLink("Kategoriju sarasas", "Kategorijos")
    </div>
</div>
<br />
<br />
<br />
<label>Pamokos:</label>
<div>
    <div>
        @Html.ActionLink("Pamoku sarasas", "AdminSarasas")
    </div>
    <div>
        @Html.ActionLink("Prideti pamoka", "Prideti", "Admin")
    </div>
</div>
<br />
<br />
<br />
<label>Testai:</label>
<div>
    <div>
        @Html.ActionLink("Testų sarasas", "AdminSarasas")
    </div>
    <div>
        @Html.ActionLink("Prideti Testa", "PridetiTesta")
    </div>
    <br/>
    <br/>
    <br/>
    <label>Praktine dalis:</label>
    <div>
        <div>
            @Html.ActionLink("Praktikų sarasas", "AdminSarasas")
        </div>
        <div>
            @Html.ActionLink("Prideti praktika", "PridetiPraktika")
        </div>
    </div>
</div>

Darbas/Darbas/Views/Admin/Kategorijos.cshtml
@using Darbas.Models

@model IEnumerable<Darbas.Kategorija>

@{
    ViewBag.Title = "Sarasas";
}

<h2>Sarasas</h2>
<div>
    <ul>
        @foreach (Kategorija kategorija in @Model)
        {
            <li>
                @Html.ActionLink(kategorija.KategorijosPavadinimas, "Sarasas", "Pamoka", new {@id = kategorija.Id}, null) |
                @Html.ActionLink("Trinti", "TrintiKategorija", new {@id = kategorija.Id})|
            </li>

        }

    </ul>
</div>

@foreach (Kategorija kategorija in @Model)
{
   
      
        <div class="course-tiles-row row">
            <div class="course-tile small-6 medium-3 column">
                <div class="course-tile-image">
                    <a href=@Url.Action("AdminSarasas")>
                        <img src="~/Images/csharp3.png" alt="Software development" data-at2x="/content/pluralsight/en/jcr:content/main/generic_block/parsys/course_tiles/courseLanding1/image-res-retina.img.png">
                    </a>

                </div>
            </div>
        </div>

}

        @Html.ActionLink("Atgal į panelę", "Index")

Darbas/Darbas/Views/Admin/Part5.cshtml
@{
    ViewBag.Title = "Part5";
}

<h2>Part5 - Cascade Dropdown using AngularJS and MVC4</h2>

<div ng-controller="Part5Controller">
    Country : <select ng-model="CountryID" ng-options="I.CountryID as I.CountryName for I in CountryList" ng-change="GetState()">
        <option value="">Select Country</option>
    </select>
    State : <select ng-model="StateID" ng-options="I.StateID as I.StateName for I in StateList">
        <option value="">{{StateTextToShow}}</option>
    </select>
    <input type="button" value="Get Selected Values" ng-click="ShowResult()" />
    <div style="padding:10px; font-weight:bold; border:1px solid #f3f3f3">
        {{Result}}
    </div>
</div>

@section scripts{
    <script src="~/Scripts/AngularController/Part5Controller.js"></script>
}

Darbas/Darbas/Views/Admin/PraktikosDetales.cshtml
@{
    ViewBag.Title = "PridetiPraktika";
}

<h2>PridetiPraktika</h2>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>jQuery UI Sortable - Drop placeholder</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <link rel="stylesheet" href="/resources/demos/style.css">
    <style>
        #sortable {
            list-style-type: none;
            margin: 0;
            padding: 0;
            width: 60%;
        }

            #sortable li {
                margin: 0 5px 5px 5px;
                padding: 5px;
                font-size: 1.2em;
                height: 1.5em;
            }

            html > body #sortable li {
                height: 1.5em;
                line-height: 1.2em;
            }

        .ui-state-highlight {
            height: 1.5em;
            line-height: 1.2em;
        }
    </style>
    <script>
  $(function() {
    $( "#sortable" ).sortable({
      placeholder: "ui-state-highlight"
    });
    $( "#sortable" ).disableSelection();
  });
    </script>
</head>
<body>

    <ul id="sortable">
        <li class="ui-state-default">Item 1</li>
        <li class="ui-state-default">Item 2</li>
        <li class="ui-state-default">Item 3</li>
        <li class="ui-state-default">Item 4</li>
        <li class="ui-state-default">Item 5</li>
        <li class="ui-state-default">Item 6</li>
        <li class="ui-state-default">Item 7</li>
    </ul>

</body>
</html>

Darbas/Darbas/Views/Admin/Prideti.cshtml
@model Darbas.Pamoka

@{
    ViewBag.Title = "Prideti";
}

<h2>Prideti</h2>

@using (Html.BeginForm("Prideti", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Pamoka</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Pavadinimas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pavadinimas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pavadinimas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KategorijosID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.KategorijosID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.KategorijosID, "", new { @class = "text-danger" })*@
                @Html.DropDownListFor(model => model.KategorijosID, ViewData["JobTitle"] as IEnumerable<SelectListItem>, "(none)")
            </div>
        </div>

        <form action="" method="post" enctype="multipart/form-data">

            <div class="form-group">
                @Html.LabelFor(model => model.FailoPavadinimas, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="Failas" id="Failas" />
                    @Html.ValidationMessageFor(model => model.FailoPavadinimas, "", new { @class = "text-danger" })
                </div>
            </div>
        </form>

        <div class="form-group">
            @Html.LabelFor(model => model.VideoNuoroda, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoNuoroda, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoNuoroda, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TestoID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TestoID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TestoID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PraktikosID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PraktikosID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PraktikosID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RezultatoID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RezultatoID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RezultatoID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@if (TempData["Ikelta"] != null)
{
    <p class="alert alert-success" id="successMessage">@TempData["Ikelta"]</p>
}
@if (TempData["Klaida"] != null)
{
    <p class="alert alert-danger" id="successMessage">@TempData["Klaida"]</p>
}
@if (TempData["Failas"] != null)
{
    <p class="alert alert-warning" id="successMessage">@TempData["Failas"]</p>
}

@if (TempData["PDF"] != null)
{
    <p class="alert alert-warning" id="successMessage">@TempData["PDF"]</p>
}
@if (TempData["Dydis"] != null)
{
    <p class="alert alert-warning" id="successMessage">@TempData["Dydis"]</p>
}
@if (TempData["Nepasirinktas"] != null)
{
    <p class="alert alert-warning" id="successMessage">@TempData["Nepasirinktas"]</p>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Darbas/Darbas/Views/Admin/PridetiPraktika.cshtml
@{
    ViewBag.Title = "PridetiPraktika";
}

<h2>PridetiPraktika</h2>

<form method="post">

    @using (Html.BeginForm("PridetiTesta", "Admin"))
    {
        <table cellspacing="2" cellpadding="2">
            <tr>
                <td>
                    Kategorija:
                </td>
                <td>
                    @Html.DropDownList("CategoryType")
                </td>
            </tr>

            <tr>
                <td>
                    Pamoka:
                </td>
                <td>
                    @Html.DropDownList("SubCategory", new SelectList(string.Empty, "Value", "Text"), "Pasirinkite pamoka", new { style = "width:250px" })
                </td>
            </tr>
        </table>
        if (TempData["nerakategorijos"] != null)
        {
            <p class="alert alert-warning" id="successMessage">@TempData["nerakategorijos"]</p>
        }

        if (TempData["nerapamokos"] != null)
        {
            <p class="alert alert-warning" id="successMessage">@TempData["nerapamokos"]</p>
        }

        <script src="~/Scripts/jquery-1.10.2.min.js"></script>
        <script type="text/javascript">

            $(document).ready(function () {

                $("#CategoryType").change(function () {

                    $("#SubCategory").empty();

                    $.ajax({
                        type: 'POST',

                        url: '@Url.Action("GetSubCategories")',
                        dataType: 'json',
                        data: { id: $("#CategoryType").val() },
                        success: function (subcategories) {

                            $.each(subcategories, function (i, subcategory) {

                                $("#SubCategory").append('<option value="'
                                    + subcategory.Value + '">' +
                                    subcategory.Text + '</option>');
                            });
                            alert(subcategory.Value)
                        },
                        error: function (ex) {
                            alert('Failed to retrieve Sub Categories : ' + ex);
                        }
                    });
                    return false;
                })
            });
        </script>

        <a style="margin: 10px 0;" href="javascript:addRow();">Prideti klausima</a>
        <table id="formTable">
            <thead>
                <tr>
                    <th>Variantas</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><textarea rows="4" cols="50" name="variantas"></textarea></td>
                </tr>
            </tbody>
        </table>
        <input type="submit" value="Submit" />


        if (TempData["Klausimas"] != null)
        {
            <p class="alert alert-warning" id="successMessage">@TempData["Klausimas"]</p>
        }
        if (TempData["Atsakymas"] != null)
        {
            <p class="alert alert-warning" id="successMessage">@TempData["Atsakymas"]</p>
        }

        <script type="text/javascript" src="~/Scripts/jquery-1.10.2.min.js"></script>
        <script type="text/javascript">
            function addRow() {
                //copy the table row and clear the value of the input, then append the row to the end of the table
                $("#formTable tbody tr:first").clone().find("input").each(function () {
                    $(this).val('');
                }).end().appendTo("#formTable");
            }
        </script>
    }
</form>

Darbas/Darbas/Views/Admin/PridetiTesta.cshtml
@model Darbas.Models.DropDown

@{
    ViewBag.Title = "Prideti testa";
}

<form method="post">

    @using (Html.BeginForm("PridetiTesta", "Admin"))
    {
        <table cellspacing="2" cellpadding="2">
            <tr>
                <td>
                    Kategorija:
                </td>
                <td>
                    @Html.DropDownList("CategoryType")
                </td>
            </tr>

            <tr>
                <td>
                    Pamoka:
                </td>
                <td>
                    @Html.DropDownList("SubCategory", new SelectList(string.Empty, "Value", "Text"), "Pasirinkite pamoka", new { style = "width:250px" })
                </td>
            </tr>
        </table>
        if (TempData["nerakategorijos"] != null)
        {
            <p class="alert alert-warning" id="successMessage">@TempData["nerakategorijos"]</p>
        }

        if (TempData["nerapamokos"] != null)
        {
            <p class="alert alert-warning" id="successMessage">@TempData["nerapamokos"]</p>
        }

        <script src="~/Scripts/jquery-1.10.2.min.js"></script>
        <script type="text/javascript">

            $(document).ready(function () {

                $("#CategoryType").change(function () {

                    $("#SubCategory").empty();

                    $.ajax({
                        type: 'POST',

                        url: '@Url.Action("GetSubCategories")',
                        dataType: 'json',
                        data: { id: $("#CategoryType").val() },
                        success: function (subcategories) {

                            $.each(subcategories, function (i, subcategory) {

                                $("#SubCategory").append('<option value="'
                                    + subcategory.Value + '">' +
                                    subcategory.Text + '</option>');
                            });
                            alert(subcategory.Value)
                        },
                        error: function (ex) {
                            alert('Failed to retrieve Sub Categories : ' + ex);
                        }
                    });
                    return false;
                })
            });
        </script>

        <a style="margin: 10px 0;" href="javascript:addRow();">Prideti klausima</a>
        <table id="formTable">
            <thead>
                <tr>
                    <th>Klausimas</th>
                    <th>Atsakymas1</th>
                    <th>Atsakymas2</th>
                    <th>Atsakymas3</th>
                    <th>Teisingas</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><input type="text" name="klausimas"/></td>
                    <td><input type="text" name="atsakymas"/></td>
                    <td><input type="text" name="atsakymas"/></td>
                    <td><input type="text" name="atsakymas"/></td>
                    <td><input type="text" name="teisingas" /></td>
                </tr>
            </tbody>
        </table>
        <input type="submit" value="Submit" />


        if (TempData["Klausimas"] != null)
        {
            <p class="alert alert-warning" id="successMessage">@TempData["Klausimas"]</p>
        }
        if (TempData["Atsakymas"] != null)
        {
            <p class="alert alert-warning" id="successMessage">@TempData["Atsakymas"]</p>
        }

        <script type="text/javascript" src="~/Scripts/jquery-1.10.2.min.js"></script>
        <script type="text/javascript">
            function addRow() {
                //copy the table row and clear the value of the input, then append the row to the end of the table
                $("#formTable tbody tr:first").clone().find("input").each(function() {
                    $(this).val('');
                }).end().appendTo("#formTable");
            }
        </script>
    }
</form>

Darbas/Darbas/Views/Admin/Trinti.cshtml
@model Darbas.Pamoka

@{
    ViewBag.Title = "Trinti";
}

<h2>Trinti</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pamoka</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Pavadinimas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pavadinimas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KategorijosID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KategorijosID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FailoPavadinimas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FailoPavadinimas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VideoNuoroda)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VideoNuoroda)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TestoID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TestoID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PraktikosID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PraktikosID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RezultatoID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RezultatoID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "AdminSarasas")
        </div>
    }
</div>