Darbas/Darbas/Controllers/PamokaController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Darbas.Views.Kategorija
{
    public class PamokaController : Controller
    { 
        DuombazeEntities db = new DuombazeEntities();
        private bool exists = false;
        Pamoka temp;
        // GET: Pamoka

        [HttpGet]
        public ActionResult Sarasas(int id)
        {
            var da = db.Pamokas.Where(pam => pam.KategorijosID == id);
            return View(da);
        }

        [HttpGet]
        public ActionResult Detales(int id)
        {
            Pamoka pamoka = db.Pamokas.Single(pam => pam.Id == id);
            return View(pamoka);
        }

       

    }
}

Darbas/Darbas/Controllers/PraktikaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Darbas.Controllers
{
    public class PraktikaController : Controller
    {
        DuombazeEntities db = new DuombazeEntities();
        
     
        // GET: Praktika
        [HttpGet, ValidateInput(false)]
        public ActionResult Detales(int id)
        {
            var pr = db.Praktikas.Single(x => x.PamokosID == id);

            var ids = pr.Variantai.Split('$');

            var variants = db.Variantais.ToList();
            
            List<string> a = new List<string>();
            foreach (var variant in variants)
            {
                foreach (var aidizas in ids)
                {
                    if (aidizas.Equals(variant.Id.ToString()))
                    {
                        a.Add(variant.Variantas);
                    }
                }
                
            }
            List<string> b = new List<string>();
            StringBuilder builder = new StringBuilder();
            foreach (string aa in a) // Loop through all strings
            {
                builder.Append(aa).Append("|"); // Append string to StringBuilder
            }
            string result = builder.ToString(); // Get string from StringBuilder
            string result1 = "";
            do
            {
                builder.Clear();
                Random rand = new Random();
                b = a.OrderBy(c => rand.Next()).ToList();
                foreach (string bb in b) // Loop through all strings
                {
                    builder.Append(bb).Append("|"); // Append string to StringBuilder
                }
                result1 = builder.ToString(); // Get string from StringBuilder
            }
            while (result.Equals(result1));
             
            ViewBag.Kls = b;
            ViewBag.Id = id;
            return View();
        }
        [HttpPost, ActionName("Detales"), ValidateInput(false) ]
        public ActionResult DetalesConfirmed(FormCollection form, int id)
        {
            var pr = db.Praktikas.Single(x => x.PamokosID == id);

            var ids = pr.Variantai.Split('$');

            var variants = db.Variantais.ToList();

            List<string> a = new List<string>();
            foreach (var variant in variants)
            {
                foreach (var aidizas in ids)
                {
                    if (aidizas.Equals(variant.Id.ToString()))
                    {
                        a.Add(variant.Variantas);
                    }
                }

            }
            StringBuilder builder = new StringBuilder();
            foreach (string aa in a) // Loop through all strings
            {
                builder.Append(aa).Append(","); // Append string to StringBuilder
            }
            string result = builder.ToString();
            var newresult  = result.Substring(0, result.Length - 1);
            List<string> abc = new List<string>();
            foreach (var item in a)
            {
                abc.Add(item);
            }
            ViewBag.Ats = abc;
           
            ViewBag.Id = id;
            var kazkas = form["variantas"];
            ViewBag.Kls = kazkas.Split(',');
            if (newresult.Equals(kazkas))
            {
                TempData["teisingas"] = "Tesiginai";
            }
            else
            {
                TempData["neteisingas"] = "Neteisingai";
            }
            return View();
        }
    }
}

Darbas/Darbas/Controllers/TestasController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Darbas.Controllers
{
    public class TestasController : Controller
    {
        private DuombazeEntities db = new DuombazeEntities();
        [HttpGet]
        public ActionResult Detales(int id)
        {
            List<Klausima> klausimas = new List<Klausima>();
            List<Atsakyma> atsakymai = new List<Atsakyma>();
            ViewBag.Pasirinkta = id;
            foreach (Klausima kls in db.Klausimas)
            {
                if (kls.PamokosID == id)
                {
                    klausimas.Add(kls);
                    foreach (Atsakyma ats in db.Atsakymas)
                    {
                        if (ats.KlausimoID == kls.Id)
                        {
                            atsakymai.Add(ats);
                        }
                    }
                }
            }
            ViewBag.Kls = klausimas;
            ViewBag.Ats = atsakymai;
            ViewBag.True = null;
           return View();
        }
        [HttpPost, ActionName("Detales")]
        public ActionResult DetalesConfirm(FormCollection form, int id)
        {
            List<Klausima> klausimas = new List<Klausima>();
            List<Atsakyma> atsakymai = new List<Atsakyma>();
            ViewBag.Pasirinkta = id;
            foreach (Klausima kls in db.Klausimas)
            {
                if (kls.PamokosID == id)
                {
                    klausimas.Add(kls);
                    foreach (Atsakyma ats in db.Atsakymas)
                    {
                        if (ats.KlausimoID == kls.Id)
                        {
                            atsakymai.Add(ats);
                        }
                    }
                }
            }
            ViewBag.Kls = klausimas;
            ViewBag.Ats = atsakymai;

            List<int> atsakymas = new List<int>();
            foreach (var kat in klausimas)
            {
                var a = form[kat.Id.ToString()];
                 atsakymas.Add(Convert.ToInt32(a));
            }
            int teisingas = 0;

            foreach (var ats in atsakymas)
            {
                foreach (var atsakyma in db.Atsakymas)
                {
                    if (atsakyma.Id == ats)
                    {
                        if (atsakyma.Teisingas == true)
                        {
                            teisingas++;
                        }
                        break;
                    }
                }
            }
            var aaa = User.Identity.Name;
            ViewBag.True = "Rezultatas: " + teisingas.ToString() + '/' + klausimas.Count.ToString();
            return View();
            ViewBag.True = null;
        }
    }
}

Darbas/Darbas/Views/Pamoka/Detales.cshtml
@model Darbas.Pamoka

@{
    ViewBag.Title = "Detales";
}

<h2>@Html.DisplayFor(model => model.Pavadinimas)</h2>

<div width="100%" height="100%">
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Pavadinimas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pavadinimas)
        </dd>

        <br />

        <dt>
            Teorinė medžiaga :
        </dt>

        <dd>
            <div class="col-lg-12 col-md-8 col-sm-4" align="center" width="100%" height="100%">
                <object class="col-lg-12 col-md-8 col-sm-4" data=@Model.FailoPavadinimas type="application/pdf" width="560" height="500" position="center"></object>
            </div>
        </dd>

        <br />

        <dt>
            Vaizdinė medžiaga:
        </dt>

        <dd>
            <div class="col-lg-12 col-md-8 col-sm-4" align="center" width="560" height="500">
                <iframe width="420" height="315" src=@Model.VideoNuoroda></iframe>
            </div>
        </dd>

        <br />

        <dt>
            Testas :
        </dt>

        <dd>
            @Html.ActionLink("Pradeti testa", "Detales", "Testas", new {id = Model.Id}, new
       {
           @class = "openDialog",
           data_dialog_id = "aboutDialog",
           data_dialog_title = "About Us"
       })
            <script type="text/javascript">

                $.ajaxSetup({ cache: false });

                $(document).ready(function () {
                    $(".openDialog").live("click", function (e) {
                        e.preventDefault();

                        $("<div></div>")
                            .addClass("dialog")
                            .attr("id", $(this)
                                .attr("data-dialog-id"))
                            .appendTo("body")
                            .dialog({
                                title: $(this).attr("data-dialog-title"),
                                close: function () { $(this).remove(); },
                                modal: true,
                                height: 250,
                                width: 400,
                                left: 0

                            })
                            .load(this.href);
                    });

                    $(".close").live("click", function (e) {
                        e.preventDefault();
                        $(this).closest(".dialog").dialog("close");
                    });
                });
            </script>
        </dd>

        <br />

        <dt>
            Praktika :
        </dt>

        <dd>
            @Html.ActionLink("Pradeti praktika", "Detales", "Praktika", new { id = Model.Id }, null)
        </dd>

        <br />

        <dt>
            Rezultatas:
        </dt>

        <dd>
            <label>Testas:</label> 0/10
            <br />
            <label>Praktika:</label> 0/10
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Grįžti į sąrašą", "Sarasas", new {id = @Model.KategorijosID}, null)
</p>

Darbas/Darbas/Views/Pamoka/Sarasas.cshtml
@using Darbas.Models

@model IEnumerable<Darbas.Pamoka>

@{
    ViewBag.Title = "Sarasas";
}

<h2>Sarasas</h2>

<div>
    <ul>
        @foreach (Pamoka pamoka in Model)
        {
            <li>
                @Html.ActionLink(pamoka.Pavadinimas, "Detales", new { @id = pamoka.Id })
            </li>
        }
    </ul>
</div>
@Html.ActionLink("atgal i pradini", "Index", "Home")